# -*- coding: utf-8 -*-
"""
Arabic translations for AEGIS-OS v4.0
النصوص العربية لنظام إيجيس الإصدار 4.0
"""

ARABIC_TEXT = {
    # Main interface / الواجهة الرئيسية
    'main_title': 'نظام إيجيس للذكاء الفضائي المتقدم الإصدار 4.0',
    'main_subtitle': 'منصة متقدمة لذكاء الحطام الفضائي والاستدامة مع الذكاء الاصطناعي',
    'navigation': 'التنقل',
    'system_status': 'حالة النظام',
    
    # Navigation menu / قائمة التنقل
    'realtime_tracking': 'التتبع المباشر',
    'orbital_analysis': 'تحليل المدارات',
    'collision_prediction': 'التنبؤ بالتصادم',
    'atmospheric_modeling': 'نمذجة الغلاف الجوي',
    'ai_predictions': 'التنبؤات بالذكاء الاصطناعي',
    'graph_network_analysis': 'تحليل الشبكات البيانية',
    'kessler_simulation': 'محاكاة متلازمة كيسلر',
    'economic_analysis': 'التحليل الاقتصادي',
    'compliance_monitoring': 'مراقبة الامتثال',
    'scientific_tools': 'الأدوات العلمية',
    
    # System status / حالة النظام
    'tracked_objects': 'الأجسام المتتبعة',
    'solar_activity': 'النشاط الشمسي',
    'high_risk_objects': 'الأجسام عالية المخاطر',
    'predicted_collisions_24h': 'التصادمات المتوقعة (24 ساعة)',
    'loading': 'جاري التحميل...',
    'status_error': 'خطأ في حالة النظام',
    
    # Real-time tracking / التتبع المباشر
    'tracking_controls': 'ضوابط التتبع',
    'debris_category': 'فئة الحطام',
    'altitude_range_km': 'نطاق الارتفاع (كم)',
    'auto_refresh': 'التحديث التلقائي',
    'loading_data': 'جاري تحميل البيانات...',
    'data_loaded': 'تم تحميل البيانات',
    'objects': 'أجسام',
    'no_data_available': 'لا توجد بيانات متاحة',
    'error_loading_data': 'خطأ في تحميل البيانات',
    'orbital_zones_distribution': 'توزيع المناطق المدارية',
    'size_distribution': 'توزيع الأحجام',
    'size_cm': 'الحجم (سم)',
    'debris_catalog': 'كتالوج الحطام',
    'select_columns': 'اختر الأعمدة',
    'export_data': 'تصدير البيانات',
    '3d_space_debris_view': 'عرض ثلاثي الأبعاد للحطام الفضائي',
    'space_debris': 'الحطام الفضائي',
    
    # Orbital analysis / تحليل المدارات
    'sgp4_propagation': 'انتشار SGP4',
    'orbital_maneuvers': 'المناورات المدارية',
    'perturbation_analysis': 'تحليل الاضطرابات',
    'orbital_elements': 'العناصر المدارية',
    'semi_major_axis_km': 'المحور شبه الرئيسي (كم)',
    'eccentricity': 'الانحراف',
    'inclination_deg': 'الميل (درجة)',
    'raan_deg': 'الصعود الأيمن للعقدة الصاعدة (درجة)',
    'arg_perigee_deg': 'حجة الحضيض (درجة)',
    'mean_anomaly_deg': 'الشذوذ المتوسط (درجة)',
    'object_properties': 'خصائص الجسم',
    'mass_kg': 'الكتلة (كغ)',
    'cross_sectional_area_m2': 'المقطع العرضي (م²)',
    'drag_coefficient': 'معامل السحب',
    'reflectivity': 'الانعكاسية',
    'propagation_settings': 'إعدادات الانتشار',
    'propagation_duration': 'مدة الانتشار',
    'include_perturbations': 'تضمين الاضطرابات',
    'propagate_orbit': 'انتشار المدار',
    'calculating_orbit': 'جاري حساب المدار...',
    'calculation_error': 'خطأ في الحساب',
    '3d_orbital_trajectory': 'المسار المداري ثلاثي الأبعاد',
    'orbital_trajectory': 'المسار المداري',
    'altitude_vs_time': 'الارتفاع مقابل الوقت',
    'time_hours': 'الوقت (ساعات)',
    'altitude_km': 'الارتفاع (كم)',
    'orbital_statistics': 'الإحصائيات المدارية',
    'perigee_km': 'الحضيض (كم)',
    'apogee_km': 'الأوج (كم)',
    'orbital_period_min': 'الفترة المدارية (دقيقة)',
    
    # Collision prediction / التنبؤ بالتصادم
    'ai_risk_assessment': 'تقييم المخاطر بالذكاء الاصطناعي',
    'monte_carlo_analysis': 'تحليل مونت كارلو',
    'conjunction_screening': 'فحص الاقتران',
    'ai_enabled': 'الذكاء الاصطناعي مفعل',
    'ai_not_available': 'الذكاء الاصطناعي غير متاح',
    'primary_object': 'الجسم الأساسي',
    'secondary_object': 'الجسم الثانوي',
    'object_id': 'معرف الجسم',
    'analysis_window_hours': 'نافزة التحليل (ساعات)',
    'analyze_collision_risk': 'تحليل مخاطر التصادم',
    'analyzing_with_ai': 'جاري التحليل بالذكاء الاصطناعي...',
    'ai_analysis_results': 'نتائج تحليل الذكاء الاصطناعي',
    'collision_probability': 'احتمالية التصادم',
    'time_to_closest_approach': 'الوقت للاقتراب الأقرب',
    'miss_distance_km': 'مسافة الاخفاق (كم)',
    'risk_level': 'مستوى المخاطر',
    'recommendations': 'التوصيات',
    'ai_analysis_error': 'خطأ في تحليل الذكاء الاصطناعي',
    'traditional_collision_analysis': 'تحليل التصادم التقليدي',
    'run_monte_carlo': 'تشغيل مونت كارلو',
    'running_simulation': 'جاري تشغيل المحاكاة...',
    'simulations_run': 'المحاكاات المشغلة',
    
    # Atmospheric modeling / نمذجة الغلاف الجوي
    'nrlmsise00_model': 'نموذج NRLMSISE-00',
    'drag_analysis': 'تحليل السحب',
    'density_variations': 'تغيرات الكثافة',
    'latitude_deg': 'خط العرض (درجة)',
    'longitude_deg': 'خط الطول (درجة)',
    'day_of_year': 'يوم السنة',
    'solar_flux_f107': 'التدفق الشمسي F10.7',
    'solar_flux_f107_avg': 'متوسط التدفق الشمسي F10.7',
    'geomagnetic_ap': 'المؤشر المغناطيسي الأرضي Ap',
    'local_solar_time': 'التوقيت الشمسي المحلي',
    'calculate_atmosphere': 'حساب الغلاف الجوي',
    'calculating_density': 'جاري حساب الكثافة...',
    'atmospheric_results': 'نتائج الغلاف الجوي',
    'total_density': 'الكثافة الإجمالية',
    'temperature': 'درجة الحرارة',
    'pressure': 'الضغط',
    'atmospheric_composition': 'تركيب الغلاف الجوي',
    'density_altitude_profile': 'ملف ارتفاع الكثافة',
    'atmospheric_profile': 'ملف الغلاف الجوي',
    'density_kg_m3': 'الكثافة (كغ/م³)',
    'temperature_k': 'درجة الحرارة (ك)',
    
    # AI predictions / التنبؤات بالذكاء الاصطناعي
    'transformer_predictions': 'تنبؤات المحول',
    'risk_forecasting': 'التنبؤ بالمخاطر',
    'population_dynamics': 'ديناميكيات السكان',
    'upload_historical_data': 'رفع البيانات التاريخية',
    'data_preview': 'معاينة البيانات',
    'records': 'سجلات',
    'train_transformer_model': 'تدريب نموذج المحول',
    'training_model': 'جاري تدريب النموذج...',
    'model_trained_successfully': 'تم تدريب النموذج بنجاح',
    'training_accuracy': 'دقة التدريب',
    'validation_loss': 'خسارة التحقق',
    'training_samples': 'عينات التدريب',
    'future_predictions': 'التنبؤات المستقبلية',
    'prediction_horizon_days': 'أفق التنبؤ (أيام)',
    'generate_predictions': 'توليد التنبؤات',
    'generating_predictions': 'جاري توليد التنبؤات...',
    'historical_risk': 'المخاطر التاريخية',
    'predicted_risk': 'المخاطر المتوقعة',
    'collision_risk_prediction': 'التنبؤ بمخاطر التصادم',
    'date': 'التاريخ',
    'collision_risk': 'مخاطر التصادم',
    'insufficient_data_for_training': 'بيانات غير كافية للتدريب',
    'training_error': 'خطأ في التدريب',
    'file_processing_error': 'خطأ في معالجة الملف',
    'upload_data_to_continue': 'رفع البيانات للمتابعة',
    'run_demo_prediction': 'تشغيل التنبؤ التجريبي',
    'running_demo': 'جاري تشغيل العرض التجريبي...',
    'demo_results': 'نتائج العرض التجريبي',
    'predicted_collision_risk': 'مخاطر التصادم المتوقعة',
    'demo_collision_predictions': 'تنبؤات التصادم التجريبية',
    'time_steps': 'خطوات الزمن',
    
    # Graph network analysis / تحليل الشبكات البيانية
    'graph_network_description': 'تحليل الشبكات البيانية للأجسام المدارية وتفاعلاتها المعقدة',
    'orbital_network': 'الشبكة المدارية',
    'collision_network': 'شبكة التصادم',
    'influence_analysis': 'تحليل التأثير',
    
    # Kessler simulation / محاكاة متلازمة كيسلر
    'kessler_description': 'محاكاة متلازمة كيسلر - السيناريو الكارثي لتصادمات الحطام الفضائي المتتالية',
    'simulation_parameters': 'معاملات المحاكاة',
    'initial_debris_count': 'عدد الحطام الأولي',
    'simulation_duration_years': 'مدة المحاكاة (سنوات)',
    'collision_probability_threshold': 'عتبة احتمالية التصادم',
    'fragmentation_multiplier': 'مضاعف التفتت',
    'scenario_selection': 'اختيار السيناريو',
    'select_scenario': 'اختر السيناريو',
    'business_as_usual': 'الأعمال كالمعتاد',
    'active_debris_removal': 'إزالة الحطام النشطة',
    'major_collision_event': 'حدث تصادم كبير',
    'solar_maximum_period': 'فترة الذروة الشمسية',
    'complete_launch_moratorium': 'وقف الإطلاق الكامل',
    'mega_constellation_deployment': 'نشر الكوكبات الضخمة',
    'advanced_parameters': 'المعاملات المتقدمة',
    'atmospheric_model': 'نموذج الغلاف الجوي',
    'mitigation_effectiveness': 'فعالية التخفيف',
    'launch_rate_modifier': 'معدل الإطلاق المعدل',
    'run_kessler_simulation': 'تشغيل محاكاة كيسلر',
    'simulation_results': 'نتائج المحاكاة',
    'total_debris': 'إجمالي الحطام',
    'annual_collisions': 'التصادمات السنوية',
    'years': 'السنوات',
    'debris_count': 'عدد الحطام',
    'collisions_per_year': 'التصادمات في السنة',
    'kessler_cascade_progression': 'تقدم التسلسل الكارثي لكيسلر',
    'final_debris_count': 'العدد النهائي للحطام',
    'annual_growth_rate': 'معدل النمو السنوي',
    'total_collisions': 'إجمالي التصادمات',
    'kessler_onset_year': 'سنة بداية كيسلر',
    'risk_assessment': 'تقييم المخاطر',
    'kessler_syndrome_triggered': 'تم تفعيل متلازمة كيسلر',
    'high_cascade_risk': 'مخاطر تسلسل عالية',
    'manageable_debris_environment': 'بيئة حطام قابلة للإدارة',
    'simulation_error': 'خطأ في المحاكاة',
    'urgent_debris_removal_needed': 'هناك حاجة ملحة لإزالة الحطام',
    'implement_launch_moratorium': 'تنفيذ وقف الإطلاق',
    'accelerate_adr_technology': 'تسريع تقنية إزالة الحطام النشطة',
    'kessler_cascade_predicted': 'تم التنبؤ بالتسلسل الكارثي لكيسلر في عام',
    'strengthen_debris_mitigation_guidelines': 'تعزيز إرشادات تخفيف الحطام',
    'increase_international_cooperation': 'زيادة التعاون الدولي',
    
    # Economic analysis / التحليل الاقتصادي
    'debris_removal_economics': 'اقتصاديات إزالة الحطام',
    'market_analysis': 'تحليل السوق',
    'policy_impact': 'تأثير السياسة',
    'mission_parameters': 'معاملات المهمة',
    'target_debris_objects': 'أهداف أجسام الحطام',
    'average_mass_kg': 'متوسط الكتلة (كغ)',
    'removal_efficiency': 'كفاءة الإزالة',
    'mission_duration_years': 'مدة المهمة (سنوات)',
    'cost_parameters': 'معاملات التكلفة',
    'launch_cost_per_kg_usd': 'تكلفة الإطلاق لكل كغ (دولار أمريكي)',
    'removal_system_cost_musd': 'تكلفة نظام الإزالة (مليون دولار أمريكي)',
    'operations_cost_per_year_musd': 'تكلفة العمليات في السنة (مليون دولار أمريكي)',
    'calculate_economics': 'حساب الاقتصاديات',
    'calculating_costs': 'جاري حساب التكاليف...',
    'economic_results': 'النتائج الاقتصادية',
    'total_mission_cost': 'إجمالي تكلفة المهمة',
    'material_recovery_value': 'قيمة استرداد المواد',
    'net_cost': 'التكلفة الصافية',
    'cost_per_object': 'التكلفة لكل جسم',
    'cost_breakdown_chart': 'مخطط تفصيل التكلفة',
    'cost_category': 'فئة التكلفة',
    'cost_millions_usd': 'التكلفة (ملايين الدولارات الأمريكية)',
    'system_development': 'تطوير النظام',
    'launch_costs': 'تكاليف الإطلاق',
    'operations': 'العمليات',
    'material_recovery': 'استرداد المواد',
    'sensitivity_analysis': 'تحليل الحساسية',
    'launch_cost_sensitivity': 'حساسية تكلفة الإطلاق',
    'net_mission_cost': 'تكلفة المهمة الصافية',
    'net_cost_millions_usd': 'التكلفة الصافية (ملايين الدولارات الأمريكية)',
    'roi_analysis': 'تحليل عائد الاستثمار',
    'avoided_damage_costs': 'تكاليف الأضرار المتجنبة',
    'return_on_investment': 'عائد الاستثمار',
    
    # Compliance monitoring / مراقبة الامتثال
    'iso_27852_description': 'مراقبة الامتثال لمعيار ISO 27852:2023 للحد من الحطام الفضائي',
    'compliance_dashboard': 'لوحة معلومات الامتثال',
    'compliance_overview': 'نظرة عامة على الامتثال',
    'detailed_analysis': 'التحليل التفصيلي',
    'post_mission_disposal': 'التخلص من المهمة اللاحقة',
    'collision_avoidance': 'تجنب التصادم',
    'debris_mitigation': 'تخفيف الحطام',
    'passivation': 'التفعيل السلبي',
    'break_up_prevention': 'منع التفكك',
    'select_requirement': 'اختر المطلب',
    'analyzing': 'جاري التحليل',
    'compliance_trend': 'اتجاه الامتثال',
    'compliance_threshold': 'عتبة الامتثال',
    'compliance_percentage': 'نسبة الامتثال',
    'improvement_recommendations': 'توصيات التحسين',
    'improve_compliance_for': 'تحسين الامتثال لـ',
    'conduct_detailed_audit': 'إجراء تدقيق تفصيلي',
    'implement_corrective_measures': 'تنفيذ التدابير التصحيحية',
    'reverse_declining_trend': 'عكس الاتجاه المتراجع',
    'investigate_root_causes': 'التحقق من الأسباب الجذرية',
    'regular_monitoring_recommended': 'يوصى بالمراقبة المنتظمة',
    
    # Scientific tools / الأدوات العلمية
    'coordinate_transformations': 'تحويلات الإحداثيات',
    'orbital_mechanics_tools': 'أدوات الميكانيكا المدارية',
    'statistical_analysis': 'التحليل الإحصائي',
    'data_validation': 'التحقق من صحة البيانات',
    'research_tools': 'أدوات البحث',
    'select_tool_category': 'اختر فئة الأداة',
    'orbital_element_converter': 'محول العناصر المدارية',
    'conjunction_analysis': 'تحليل الاقتران',
    'debris_flux_analysis': 'تحليل تدفق الحطام',
    'solar_activity_correlation': 'ارتباط النشاط الشمسي',
    'keplerian_elements': 'العناصر الكبلرية',
    'convert_to_cartesian': 'تحويل إلى ديكارتي',
    'cartesian_coordinates': 'الإحداثيات الديكارتية',
    'derived_parameters': 'المعاملات المشتقة',
    'conversion_error': 'خطأ في التحويل',
    
    # General UI elements / عناصر واجهة المستخدم العامة
    'loading_text': 'جاري التحميل...',
    'error_text': 'خطأ',
    'success_text': 'نجح',
    'warning_text': 'تحذير',
    'info_text': 'معلومات',
    'close': 'إغلاق',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'submit': 'إرسال',
    'reset': 'إعادة تعيين',
    'refresh': 'تحديث',
    'download': 'تنزيل',
    'upload': 'رفع',
    'search': 'بحث',
    'filter': 'تصفية',
    'sort': 'ترتيب',
    'expand': 'توسيع',
    'collapse': 'طي',
    'next': 'التالي',
    'previous': 'السابق',
    'first': 'الأول',
    'last': 'الأخير',
    'total': 'إجمالي',
    'average': 'متوسط',
    'minimum': 'أدنى',
    'maximum': 'أقصى',
    'standard_deviation': 'الانحراف المعياري',
    'confidence_interval': 'فترة الثقة',
    'probability': 'الاحتمالية',
    'frequency': 'التكرار',
    'distribution': 'التوزيع',
    'correlation': 'الارتباط',
    'regression': 'الانحدار',
    'classification': 'التصنيف',
    'clustering': 'التجميع',
    'optimization': 'التحسين',
    'validation': 'التحقق',
    'verification': 'التحقق من الصحة',
    'calibration': 'المعايرة',
    'estimation': 'التقدير',
    'prediction': 'التنبؤ',
    'simulation': 'المحاكاة',
    'modeling': 'النمذجة',
    'analysis': 'التحليل',
    'synthesis': 'التركيب',
    'evaluation': 'التقييم',
    'assessment': 'التقدير',
    'monitoring': 'المراقبة',
    'tracking': 'التتبع',
    'surveillance': 'المراقبة',
    'detection': 'الكشف',
    'identification': 'التعريف',
    'recognition': 'التعرف',
    'classification_accuracy': 'دقة التصنيف',
    'precision': 'الدقة',
    'recall': 'الاستدعاء',
    'f1_score': 'نقاط F1',
    'sensitivity': 'الحساسية',
    'specificity': 'النوعية',
    'accuracy': 'الدقة',
    'error_rate': 'معدل الخطأ',
    'false_positive': 'إيجابي كاذب',
    'false_negative': 'سلبي كاذب',
    'true_positive': 'إيجابي حقيقي',
    'true_negative': 'سلبي حقيقي',
    'confusion_matrix': 'مصفوفة الالتباس',
    'roc_curve': 'منحنى ROC',
    'auc_score': 'نقاط AUC',
    'cross_validation': 'التحقق المتقاطع',
    'hyperparameter_tuning': 'ضبط المعاملات الفائقة',
    'feature_selection': 'اختيار الميزات',
    'feature_engineering': 'هندسة الميزات',
    'data_preprocessing': 'معالجة البيانات المسبقة',
    'data_cleaning': 'تنظيف البيانات',
    'data_transformation': 'تحويل البيانات',
    'data_normalization': 'تطبيع البيانات',
    'data_standardization': 'توحيد البيانات',
    'outlier_detection': 'كشف القيم الشاذة',
    'missing_value_imputation': 'إحلال القيم المفقودة',
    'dimensionality_reduction': 'تقليل الأبعاد',
    'principal_component_analysis': 'تحليل المكونات الرئيسية',
    'independent_component_analysis': 'تحليل المكونات المستقلة',
    'linear_discriminant_analysis': 'تحليل التمييز الخطي',
    'manifold_learning': 'تعلم المتعددات',
    'clustering_analysis': 'تحليل التجميع',
    'hierarchical_clustering': 'التجميع الهرمي',
    'k_means_clustering': 'تجميع K-means',
    'dbscan_clustering': 'تجميع DBSCAN',
    'gaussian_mixture_models': 'نماذج الخليط الغاوسي',
    'anomaly_detection': 'كشف الشذوذ',
    'novelty_detection': 'كشف الجدة',
    'change_point_detection': 'كشف نقاط التغيير',
    'trend_analysis': 'تحليل الاتجاه',
    'seasonality_analysis': 'تحليل الموسمية',
    'time_series_analysis': 'تحليل السلاسل الزمنية',
    'time_series_forecasting': 'التنبؤ بالسلاسل الزمنية',
    'autoregressive_models': 'النماذج الانحدارية التلقائية',
    'moving_average_models': 'نماذج المتوسط المتحرك',
    'exponential_smoothing': 'التنعيم الأسي',
    'state_space_models': 'نماذج فضاء الحالة',
    'kalman_filtering': 'ترشيح كالمان',
    'particle_filtering': 'ترشيح الجسيمات',
    'monte_carlo_methods': 'طرق مونت كارلو',
    'bayesian_inference': 'الاستدلال البايزي',
    'maximum_likelihood_estimation': 'تقدير الاحتمالية القصوى',
    'method_of_moments': 'طريقة العزوم',
    'least_squares_estimation': 'تقدير المربعات الصغرى',
    'robust_estimation': 'التقدير المقاوم',
    'regularization': 'التنظيم',
    'ridge_regression': 'انحدار ريدج',
    'lasso_regression': 'انحدار لاسو',
    'elastic_net_regression': 'انحدار الشبكة المرنة',
    'logistic_regression': 'الانحدار اللوجستي',
    'polynomial_regression': 'الانحدار متعدد الحدود',
    'nonlinear_regression': 'الانحدار غير الخطي',
    'support_vector_machines': 'آلات الدعم المتجه',
    'decision_trees': 'أشجار القرار',
    'random_forests': 'الغابات العشوائية',
    'gradient_boosting': 'تعزيز التدرج',
    'neural_networks': 'الشبكات العصبية',
    'deep_learning': 'التعلم العميق',
    'convolutional_neural_networks': 'الشبكات العصبية التحويلية',
    'recurrent_neural_networks': 'الشبكات العصبية المتكررة',
    'long_short_term_memory': 'الذاكرة طويلة المدى القصيرة',
    'transformer_models': 'نماذج المحول',
    'attention_mechanisms': 'آليات الانتباه',
    'graph_neural_networks': 'الشبكات العصبية البيانية',
    'reinforcement_learning': 'التعلم المعزز',
    'q_learning': 'تعلم Q',
    'policy_gradient_methods': 'طرق تدرج السياسة',
    'actor_critic_methods': 'طرق الممثل الناقد',
    'multi_agent_systems': 'أنظمة متعددة الوكلاء',
    'federated_learning': 'التعلم الموحد',
    'transfer_learning': 'التعلم النقلي',
    'meta_learning': 'التعلم الفوقي',
    'few_shot_learning': 'التعلم بعدد قليل من الأمثلة',
    'zero_shot_learning': 'التعلم بدون أمثلة',
    'self_supervised_learning': 'التعلم ذاتي الإشراف',
    'unsupervised_learning': 'التعلم غير المشرف',
    'semi_supervised_learning': 'التعلم شبه المشرف',
    'active_learning': 'التعلم النشط',
    'online_learning': 'التعلم المباشر',
    'continual_learning': 'التعلم المستمر',
    'lifelong_learning': 'التعلم مدى الحياة',
    'interpretable_machine_learning': 'التعلم الآلي القابل للتفسير',
    'explainable_artificial_intelligence': 'الذكاء الاصطناعي القابل للتفسير',
    'fairness_in_machine_learning': 'العدالة في التعلم الآلي',
    'privacy_preserving_machine_learning': 'التعلم الآلي المحافظ على الخصوصية',
    'adversarial_machine_learning': 'التعلم الآلي العدائي',
    'robust_machine_learning': 'التعلم الآلي المقاوم',
    'trustworthy_artificial_intelligence': 'الذكاء الاصطناعي الجدير بالثقة',
}
